spring:
  datasource:
    username: root
    password: 2020fight@G
    url: jdbc:mysql://127.0.0.1:3306/study_data?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
